services:
  - type: web
    name: loud-snscrape
    env: node
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"  # or your custom port if needed
